// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo(in *jlexer.Lexer, out *Verb) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "infinitive":
			out.Infinitive = string(in.String())
		case "normalisedInfinitive":
			out.NormalisedInfinitive = string(in.String())
		case "english":
			out.English = string(in.String())
		case "helperID":
			out.HelperID = int(in.Int())
		case "isHelper":
			out.IsHelper = bool(in.Bool())
		case "isReflexive":
			out.IsReflexive = bool(in.Bool())
		case "conjugations":
			easyjsonD2b7633eDecode(in, &out.Conjugations)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo(out *jwriter.Writer, in Verb) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.Int(int(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"infinitive\":")
	out.String(string(in.Infinitive))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"normalisedInfinitive\":")
	out.String(string(in.NormalisedInfinitive))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"english\":")
	out.String(string(in.English))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"helperID\":")
	out.Int(int(in.HelperID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"isHelper\":")
	out.Bool(bool(in.IsHelper))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"isReflexive\":")
	out.Bool(bool(in.IsReflexive))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"conjugations\":")
	easyjsonD2b7633eEncode(out, in.Conjugations)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Verb) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Verb) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Verb) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Verb) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo(l, v)
}
func easyjsonD2b7633eDecode(in *jlexer.Lexer, out *struct{ Data []Conjugation }) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Conjugation, 0, 1)
					} else {
						out.Data = []Conjugation{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Conjugation
					(v1).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncode(out *jwriter.Writer, in struct{ Data []Conjugation }) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in.Data {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo1(in *jlexer.Lexer, out *Tense) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "identifier":
			out.Identifier = string(in.String())
		case "displayName":
			out.DisplayName = string(in.String())
		case "order":
			out.Order = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo1(out *jwriter.Writer, in Tense) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.Int(int(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"identifier\":")
	out.String(string(in.Identifier))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"displayName\":")
	out.String(string(in.DisplayName))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"order\":")
	out.Int(int(in.Order))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Tense) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Tense) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Tense) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Tense) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo1(l, v)
}
func easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo2(in *jlexer.Lexer, out *Pronoun) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "identifier":
			out.Identifier = string(in.String())
		case "displayName":
			out.DisplayName = string(in.String())
		case "reflexive":
			out.Reflexive = string(in.String())
		case "order":
			out.Order = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo2(out *jwriter.Writer, in Pronoun) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.Int(int(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"identifier\":")
	out.String(string(in.Identifier))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"displayName\":")
	out.String(string(in.DisplayName))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"reflexive\":")
	out.String(string(in.Reflexive))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"order\":")
	out.Int(int(in.Order))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pronoun) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pronoun) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pronoun) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pronoun) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo2(l, v)
}
func easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo3(in *jlexer.Lexer, out *Language) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "lang":
			out.Lang = string(in.String())
		case "code":
			out.Code = string(in.String())
		case "locale":
			out.Locale = string(in.String())
		case "version":
			out.Version = int(in.Int())
		case "schemaVersion":
			out.SchemaVersion = int(in.Int())
		case "hasReflexives":
			out.HasReflexives = bool(in.Bool())
		case "hasHelpers":
			out.HasHelpers = bool(in.Bool())
		case "tenses":
			easyjsonD2b7633eDecode1(in, &out.Tenses)
		case "pronouns":
			easyjsonD2b7633eDecode2(in, &out.Pronouns)
		case "verbs":
			easyjsonD2b7633eDecode3(in, &out.Verbs)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo3(out *jwriter.Writer, in Language) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"id\":")
	out.Int(int(in.Id))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"lang\":")
	out.String(string(in.Lang))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"code\":")
	out.String(string(in.Code))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"locale\":")
	out.String(string(in.Locale))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"version\":")
	out.Int(int(in.Version))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"schemaVersion\":")
	out.Int(int(in.SchemaVersion))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"hasReflexives\":")
	out.Bool(bool(in.HasReflexives))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"hasHelpers\":")
	out.Bool(bool(in.HasHelpers))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"tenses\":")
	easyjsonD2b7633eEncode1(out, in.Tenses)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"pronouns\":")
	easyjsonD2b7633eEncode2(out, in.Pronouns)
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"verbs\":")
	easyjsonD2b7633eEncode3(out, in.Verbs)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Language) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Language) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Language) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Language) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo3(l, v)
}
func easyjsonD2b7633eDecode3(in *jlexer.Lexer, out *struct{ Data []Verb }) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Verb, 0, 1)
					} else {
						out.Data = []Verb{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Verb
					(v4).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncode3(out *jwriter.Writer, in struct{ Data []Verb }) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in.Data {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjsonD2b7633eDecode2(in *jlexer.Lexer, out *struct{ Data []Pronoun }) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Pronoun, 0, 1)
					} else {
						out.Data = []Pronoun{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Pronoun
					(v7).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncode2(out *jwriter.Writer, in struct{ Data []Pronoun }) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in.Data {
			if v8 > 0 {
				out.RawByte(',')
			}
			(v9).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjsonD2b7633eDecode1(in *jlexer.Lexer, out *struct{ Data []Tense }) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]Tense, 0, 1)
					} else {
						out.Data = []Tense{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v10 Tense
					(v10).UnmarshalEasyJSON(in)
					out.Data = append(out.Data, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncode1(out *jwriter.Writer, in struct{ Data []Tense }) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v11, v12 := range in.Data {
			if v11 > 0 {
				out.RawByte(',')
			}
			(v12).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}
func easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo4(in *jlexer.Lexer, out *Conjugation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "conjugation":
			out.Conjugation = string(in.String())
		case "normalisedConjugation":
			out.NormalisedConjugation = string(in.String())
		case "tenseID":
			out.TenseID = int(in.Int())
		case "pronounID":
			out.PronounID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo4(out *jwriter.Writer, in Conjugation) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"conjugation\":")
	out.String(string(in.Conjugation))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"normalisedConjugation\":")
	out.String(string(in.NormalisedConjugation))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"tenseID\":")
	out.Int(int(in.TenseID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"pronounID\":")
	out.Int(int(in.PronounID))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Conjugation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Conjugation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComNoisyscannerIverbsGo4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Conjugation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Conjugation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComNoisyscannerIverbsGo4(l, v)
}
